- name: Config postgresql version 13
  hosts: all
  vars:
    postgresql_version: "13"
    postgresql_certificates:
      - name: test_crt
        dns: www.example.com
        ca: self-sign
    postgresql_ssl_enable: true
    postgresql_pg_hba_conf:
      - type: hostssl
        database: all
        user: all
        auth_method: md5
        address: '127.0.0.1/32'
    postgresql_password: mypass
    postgresql_server_conf:
      huge_pages: try
  tasks:
  - name: Configure postgresql using role
    import_role:
      name: linux-system-roles.postgresql
    become: yes
    become_user: root
