- name: mom premier playbook
  hosts: all
  remote_user: root
  become_user: yes
  tasks:
  - name: test connection
    ping:
      
  - name: create directory recurse
    file:
       path: "/root/tunisie/1/2/3"
       recurse: yes
       state: directory 
       owner: root
       group: root
       mode: 0777
      
