- name: mom premier playbook
  hosts: all
  remote_user: root
  become_user: yes
  tasks:
  - name: test connection 
    ping:
      
  - name: creation directory /tunisie
    file:
       path: "/root/tunisie"
       state: abscent 

